-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.Interface exposing (Broker(..))


type Broker
    = Broker
