-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.Mutation exposing (CreateAgentRequiredArguments, createAgent)

import Agent.InputObject
import Agent.Interface
import Agent.Object
import Agent.Scalar
import Agent.ScalarCodecs
import Agent.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateAgentRequiredArguments =
    { input : Agent.InputObject.CreateAgentInput }


{-|

  - input -

-}
createAgent : CreateAgentRequiredArguments -> SelectionSet decodesTo Agent.Object.CreateAgentPayload -> SelectionSet (Maybe decodesTo) RootMutation
createAgent requiredArgs object_ =
    Object.selectionForCompositeField "createAgent" [ Argument.required "input" requiredArgs.input Agent.InputObject.encodeCreateAgentInput ] object_ (identity >> Decode.nullable)
