-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.Object exposing (Agent(..), CreateAgentPayload(..), Superagent(..))


type Agent
    = Agent


type CreateAgentPayload
    = CreateAgentPayload


type Superagent
    = Superagent
