-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.Query exposing (BrokerRequiredArguments, broker, brokers)

import Agent.InputObject
import Agent.Interface
import Agent.Object
import Agent.Scalar
import Agent.ScalarCodecs
import Agent.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| -}
brokers : SelectionSet decodesTo Agent.Interface.Broker -> SelectionSet (List decodesTo) RootQuery
brokers object_ =
    Object.selectionForCompositeField "brokers" [] object_ (identity >> Decode.list)


type alias BrokerRequiredArguments =
    { id : Agent.ScalarCodecs.Id }


{-|

  - id -

-}
broker : BrokerRequiredArguments -> SelectionSet decodesTo Agent.Interface.Broker -> SelectionSet (Maybe decodesTo) RootQuery
broker requiredArgs object_ =
    Object.selectionForCompositeField "broker" [ Argument.required "id" requiredArgs.id (Agent.ScalarCodecs.codecs |> Agent.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)
