-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.ScalarCodecs exposing (Id, codecs)

import Agent.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Agent.Scalar.Id


codecs : Agent.Scalar.Codecs Id
codecs =
    Agent.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
