-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.Object.Agent exposing (brokerId, id, level, name)

import Agent.InputObject
import Agent.Interface
import Agent.Object
import Agent.Scalar
import Agent.ScalarCodecs
import Agent.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Agent.ScalarCodecs.Id Agent.Object.Agent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Agent.ScalarCodecs.codecs |> Agent.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
name : SelectionSet String Agent.Object.Agent
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
level : SelectionSet Int Agent.Object.Agent
level =
    Object.selectionForField "Int" "level" [] Decode.int


{-| -}
brokerId : SelectionSet Agent.ScalarCodecs.Id Agent.Object.Agent
brokerId =
    Object.selectionForField "ScalarCodecs.Id" "brokerId" [] (Agent.ScalarCodecs.codecs |> Agent.Scalar.unwrapCodecs |> .codecId |> .decoder)
