-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Agent.Object.CreateAgentPayload exposing (agent)

import Agent.InputObject
import Agent.Interface
import Agent.Object
import Agent.Scalar
import Agent.ScalarCodecs
import Agent.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
agent : SelectionSet decodesTo Agent.Object.Agent -> SelectionSet decodesTo Agent.Object.CreateAgentPayload
agent object_ =
    Object.selectionForCompositeField "agent" [] object_ identity
